# Generated by Django 3.2.6 on 2022-09-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
