# Generated by Django 3.2.6 on 2022-09-23 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='profile_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disc', to=settings.AUTH_USER_MODEL),
        ),
    ]
